language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: UqrD58Y9gwRg/h1mXzaHYsNQpyznuC6CRI8LB+9sVbzVP5LNLQchsegfS41L9G19Pq3BS14DAHMIWZDzzqlzarwfioFtA6Ogp3gNkW/bb4VIVhjT1cbQu61LI70DXXIiWyey4H5urZeX5Sxl2D7kqWS7RCFsyrxqtAzLOqqVXiy1dPWSJlO4PyO5vUqZiCIL9aQnYQhjts4gJKT2yX/V45GMCfCIdlmp40iu9zBEvcOVY62vWfV2zzqaZyrQ9fuFtu+mWjyWNc7LIUJQErB8ddeZ2kL4s4fEksYjMQoBDwi3DLnEJwF4OP/v2J7EOZv+f6sKMXuG8UBMiIhc7pKqSsxdCTKXlSUasPzz//J7cva7AhqU1tTyXgXDSR1HMDDfEG9D7MNm0np6D2K/opttswyRZRSCYxg6mQw1m5dsDwLMHxCcQeNfEskqbZQXZVKyQUBS1er/RUZ6kbsstBZfDv/rOncf3voLrt2QQbqRpMgyc96uoPrHwFbpI9F28zhlEAFr0fjwJEcN7/g/Y83sq1NlMWY4kksQ5FVygItgogaFzBuQ0gZgJ++JzwFc897R6Lei6D0SdCjP/o6z8iNikSMUNhgJxcCR2qXBfDqREmNv8HnopbXDy0qFB2UKa1u2D0kOjoAoG0g48GQNrTwfXCKf35gBhG41jC7zTos6FOk=
  app: rainbow-square-backend
  on:
    repo: djkah11/puzzle-09-2016
